### ISSUE TITLE
About figure I in the paper

### ISSUE THREAD

**Issue by lrt366** [kaniblu/ludus-jluva#1]
May I ask where this process is reflected?
p*(x) —>p^(x)->p^*(x)
thanks a lot!

**Comment by kaniblu** [comment]
Hi, the process described in figure 1 is just a general description of generative data augmentation. The code here is used for training and generating new samples only. To test the generated samples for supervised tasks, you can use any implementations such as [this](https://github.com/MiuLab/SlotGated-SLU).
